### ISSUE TITLE
Rinominare classi e campi.

### ISSUE THREAD

**Issue by FedericoGuerri** [Danny182/progettoTAP#22]
Alcune classi non hanno un nome appropriato.
Ad esempio:
-CompanyController che in realtà controlla anche invoice e client;
-Textfields nei vari pannelli non corrispondono ai nomi effettivi dei campi(nei vari client,company,invoice);

**Comment by Danny182** [comment]
AL momento HO rinominato in AppController, alla fine controlla le cose principali dell'app.

Non ho trovato textfield con nomi che non corrispondono.
