### ISSUE TITLE
Aggiungere secondo db al progetto

### ISSUE THREAD

**Issue by FedericoGuerri** [Danny182/progettoTAP#5]

**Comment by Danny182** [comment]
Direi di usare Redis.

**Comment by FedericoGuerri** [comment]
Aggiunto repository per la classe client. C'è però una Nullpointer nel redisWrapper.

**Comment by FedericoGuerri** [comment]
https://examples.javacodegeeks.com/enterprise-java/spring/spring-data-redis-example/ 
sembra fare al caso nostro.
